// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.service3;

public interface MoistureReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.MoistureReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
