// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.service3;

public interface MoistureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.MoistureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
