// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service2;

public final class LivestockDataImpl {
  private LivestockDataImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LivestockDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LivestockDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LivestockDataReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LivestockDataReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service2\"$\n\024LivestockD" +
      "ataRequest\022\014\n\004text\030\001 \001(\t\"%\n\022LivestockDat" +
      "aReply\022\017\n\007message\030\001 \001(\t2e\n\rLivestockData" +
      "\022T\n\022CheckLivestockData\022\036.service2.Livest" +
      "ockDataRequest\032\034.service2.LivestockDataR" +
      "eply\"\000B$\n\rgrpc.service2B\021LivestockDataIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_LivestockDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_LivestockDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LivestockDataRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service2_LivestockDataReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_LivestockDataReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LivestockDataReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
