// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service2;

public interface LivestockDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.LivestockDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
