// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service2;

public interface LivestockDataReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.LivestockDataReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
