// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.service1;

public final class WeatherImpl {
  private WeatherImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_WeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_WeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_WeatherReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_WeatherReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"\036\n\016WeatherReq" +
      "uest\022\014\n\004text\030\001 \001(\t\"\037\n\014WeatherReply\022\017\n\007me" +
      "ssage\030\001 \001(\t2M\n\007Weather\022B\n\014CheckWeather\022\030" +
      ".service1.WeatherRequest\032\026.service1.Weat" +
      "herReply\"\000B\036\n\rgrpc.service1B\013WeatherImpl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_WeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_WeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_WeatherRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service1_WeatherReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_WeatherReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_WeatherReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
