// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.service1;

public interface WeatherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.WeatherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
